version: '3.4'

services:
  orchestrator:
    image: ghcr.io/liquidai-project/wasmiot-orchestrator:devcontainer
    # Continue from the original (i.e., docker-compose.yml). See:
    # https://docs.docker.com/compose/extends/
    extends:
      file: docker-compose.yml
      service: orchestrator-base
    networks:
      # Only use the "orchestrator net" and not the setup that connects with
      # other hosts in LAN.
      default:
    build:
      context: .
    # VSCode + Docker Compose debugging config from:
    # https://tech.indy.fr/2022/06/10/how-to-use-vscode-debugger-with-multiple-docker-services/
    # and https://code.visualstudio.com/docs/containers/docker-compose
    # Uncomment this for debugging devcontainer locally?? (If you ever want that??)
    #ports:
    #  - 9229:9229
    command: sleep infinity
    user: node
    environment:
      NODE_ENV: development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_NODE_RESOURCE_DETECTORS: env,host,container
    volumes:
      # Mount source code on host to the container in corresponding location. NOTE
      # Mounting overwrites files/directories in image.
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      # UI
      - 16686:16686
      - 4317:4317 # HTTP/Proto collector
      - 4318:4318 # HTTP/JSON collector

      - 5775:5775/udp

    environment:
      - LOG_LEVEL=debug

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    name: wasmiot-net
