services:
  orchestrator-base:
    image: ghcr.io/liquidai-project/wasmiot-orchestrator
    build:
      context: ./fileserv
      dockerfile: ./Dockerfile
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    restart: always
    networks:
      default:
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      PUBLIC_HOST: ${PUBLIC_HOST:-}
      PUBLIC_PORT: ${PUBLIC_PORT:-3000}
    command: nodejs ./server.js

  mongo:
    image: mongo
    restart: always
    networks:
      default:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/DATA/CONFIGDB
      - mongo-db:/DATA/DB

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    # Network for the orchestrator and MongoDB.
    name: wasmiot-net
