version: '3.4'

services:
  orchestrator:
    image: ghcr.io/liquidai-project/wasmiot-orchestrator
    build:
      context: ./fileserv
      dockerfile: ./Dockerfile
      target: compose
    restart: always
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    command: nodejs ./server.js
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      PUBLIC_HOST: ${PUBLIC_HOST:-}
      PUBLIC_PORT: ${PUBLIC_PORT:-3000}

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/DATA/CONFIGDB
      - mongo-db:/DATA/DB

  mdns-reflector:
    image: flungo/avahi
    restart: always
    environment:
      REFLECTOR_ENABLE_REFLECTOR: "yes"
    networks:
      - default
      - physical

volumes:
  mongo-config:
  mongo-db:

networks:
  # Network for orchestrator and MongoDB
  default:
    name: wasmiot-net
  physical:
    name: physical
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:-eth0}
    ipam:
      config:
        - subnet: "${NETWORK_IP_BASE:-192.168.1}.0/24"
          gateway: "${NETWORK_IP_BASE:-192.168.1}.1"
