version: '3.4'

services:
  orchestrator:
    build:
      context: ./fileserv
      dockerfile: ./Dockerfile
      target: compose
    #ports:
    #  - ${PUBLIC_PORT:-3000}:3000
    networks:
      dockeripvlan:
      default: 
    command: nodejs ./server.js
    environment:
      CONFIG_MONGODB_HOST: ${MONGO_HOST:-mongo}
      CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
      CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      CONFIG_PUBLIC_HOST: ${PUBLIC_HOST:-http://orchestrator}
      CONFIG_PUBLIC_PORT: ${PUBLIC_PORT:-3000}

  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      default:
    # TODO Add volumes for db.
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/DATA/CONFIGDB
      - mongo-db:/DATA/DB

volumes:
  mongo-config:
  mongo-db:

#networks:
#  # Network where orchestrator (which could in the future be separate from the
#  # "(web)server" and its routes?) lives in.
#  default:
#    name: wasmiot-net
networks:
  default:
    name: wasmiot-net
  dockeripvlan:
    name: dockeripvlan
    driver: ipvlan
    driver_opts:
      parent: wlp0s20f3
    ipam:
      config:
        #- subnet: "192.168.43.236/24"
        #  ip_range: "192.168.43.236/24"
        #  gateway: "192.168.43.1"
        - subnet: "10.0.0.0/16"
          ip_range: "10.0.0.0/16"
          gateway: "10.0.0.1"
