version: '3.4'

services:
  orchestrator:
    # Continue from the original (i.e., docker-compose.yml). See:
    # https://docs.docker.com/compose/extends/
    extends:
      file: docker-compose.yml
      service: orchestrator
    networks:
      # Only use the "orchestrator net" and not the setup that connects with
      # other hosts in LAN.
      default:
    build:
      # For debugging the whole project directory needs to be available, not
      # just `fileserv`.
      context: .
      dockerfile: ./fileserv/Dockerfile
      target: devcontainer
    # VSCode + Docker Compose debugging config from:
    # https://tech.indy.fr/2022/06/10/how-to-use-vscode-debugger-with-multiple-docker-services/
    # and https://code.visualstudio.com/docs/containers/docker-compose
    # Uncomment this for debugging devcontainer locally?? (If you ever want that??)
    #ports:
    #  - 9229:9229
    command: sleep infinity
    environment:
      NODE_ENV: development
    volumes:
    # Mount source code on host to the container in corresponding location. NOTE
    # Mounting overwrites files/directories in image.
      - .:/app

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    name: wasmiot-net