version: '3.4'

services:
  orchestrator:
    build:
      context: ./fileserv
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command: nodejs ./server.js
    # TODO Add volumes for db.
    environment:
      # TODO These should not be these + use a local .env file instead.
      CONFIG_MONGODB_ADMINUSERNAME: root
      CONFIG_MONGODB_ADMINPASSWORD: example
      #CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  # TODO Set IOT-device hostnames to end with ".local."? Considered using `domainname`
  # (see https://docs.docker.com/compose/compose-file/#domainname) but had no
  # luck.
  node-device:
    build:
      context: ./client
      dockerfile: ../fileserv/Dockerfile
    ports:
      - 3002:3002
    command: nodejs mdnsDevice.js 3002

  flask-device:
    build:
      context: ../flask-host/
      dockerfile: .devcontainer/Dockerfile
    command: python __main__.py
    ports:
      # 5000 is probably the default Flask-port.
      - 3001:5000

  mongo:
    image: mongo
    restart: unless-stopped
    # TODO Add volumes for db.
    environment:
      # TODO These should not be these + use a local .env file instead.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
