version: '3.4'

services:
  orchestrator-devcontainer:
    # Continue from the original (i.e., docker-compose.yml). See:
    # https://docs.docker.com/compose/extends/
    extends:
      file: docker-compose.yml
      service: orchestrator
    build:
      # For debugging the whole project directory needs to be available, not
      # just `fileserv`.
      context: .
      dockerfile: ./fileserv/Dockerfile
      target: server-debug
    ports:
      # VSCode + Docker Compose debugging config from:
      # https://tech.indy.fr/2022/06/10/how-to-use-vscode-debugger-with-multiple-docker-services/
      # and https://code.visualstudio.com/docs/containers/docker-compose
      - 9229:9229
    command: sleep infinity #echo "For debugging a script, run the app first like this: 'nodejs --inspect=0.0.0.0:9229 ./fileserv/server.js'"
    # TODO Add volumes for db.
    environment:
      NODE_ENV: development
    volumes:
      - .:/app:cached
  
  # Import the other services from original. TODO Can these be just
  # automatically "imported" from the parent compose file?
  node-device:
    extends:
      file: docker-compose.yml
      service: node-device

  flask-device:
    extends:
      file: docker-compose.yml
      service: flask-device

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

volumes:
  device1-configs:
  device1-modules:
  device1-output:
