version: '3.4'

services:
  orchestrator-base:
    build:
      context: ./fileserv
      dockerfile: ./Dockerfile
      target: compose
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    networks:
      default:
    command: nodejs ./server.js
    env_file:
      - ./.env.example
      - ./.env
    
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      default:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/DATA/CONFIGDB
      - mongo-db:/DATA/DB

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    # Network for the orchestrator and MongoDB.
    name: wasmiot-net
