version: '3.1'

services:
  debug_server:
    profiles:
      - debug
    build:
      context: .
      target: debug
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: database
      MONGO_PORT: 27017
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: example
      RUST_LOG: debug

  server:
    profiles:
      - final
    build:
      context: .
      target: final
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: database
      MONGO_PORT: 27017
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: example
      RUST_LOG: debug

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  default:
    name: wasmiot-net
