services:
  mongo:
    image: mongo:6.0.23
    container_name: wasmiot-mongodb
    restart: unless-stopped
    networks:
      database:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongo-config:/data/configdb
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: wasmiot-mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:-mongo}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${MONGO_EXPRESS_ENABLE_ADMIN:-false}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH: ${MONGO_EXPRESS_BASICAUTH:-false}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    networks:
      database:

  orchestrator:
    image: ghcr.io/liquidai-project/wasmiot-orchestrator
    container_name: wasmiot-orchestrator
    restart: unless-stopped
    depends_on:
      - mongo
    build:
      context: ../fileserv
      dockerfile: ./Dockerfile-production
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    networks:
      wasmiot:
        ipv4_address: 172.21.0.10
      database:
    environment:
      MONGO_HOST: ${MONGO_HOST:-127.0.0.1}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      PUBLIC_HOST: ${PUBLIC_HOST}
      PUBLIC_PORT: ${PUBLIC_PORT}
      WASMIOT_INIT_FOLDER: ${WASMIOT_INIT_FOLDER:-/init}
      WASMIOT_CLEAR_LOGS: ${WASMIOT_CLEAR_LOGS:-true}
    volumes:
      - ./test1/orchestrator/init:/init
      - ./test1/orchestrator/files:/app/fileserv/files

  supervisor-python-1:
    image: ghcr.io/liquidai-project/wasmiot-supervisor
    container_name: wasmiot-supervisor-python-1
    restart: unless-stopped
    depends_on:
      - orchestrator
    build:
      context: ../wasmiot-supervisor
      dockerfile: ./Dockerfile-production
    ports:
      - ${SUPERVISOR_PYTHON_1_PORT}:${SUPERVISOR_PYTHON_1_PORT}
    environment:
      FLASK_APP: supervisor-python-1
      FLASK_PORT: ${SUPERVISOR_PYTHON_1_PORT}
      FLASK_ENV: production
      FLASK_DEBUG: 0
      WASMIOT_ORCHESTRATOR_URL: ${WASMIOT_ORCHESTRATOR_URL}
      WASMIOT_LOGGING_ENDPOINT: ${WASMIOT_LOGGING_ENDPOINT}
      # EXTERNAL_LOGGING_ENABLED: true
    volumes:
      - ./test1/device-python-1/configs:/app/instance/configs
      - ./test1/device-python-1/modules:/app/instance/modules
      - ./test1/device-python-1/output:/app/instance/output
    networks:
      wasmiot:
        ipv4_address: 172.21.0.21

  supervisor-python-2:
    image: ghcr.io/liquidai-project/wasmiot-supervisor
    container_name: wasmiot-supervisor-python-2
    restart: unless-stopped
    depends_on:
      - orchestrator
    build:
      context: ../wasmiot-supervisor
      dockerfile: ./Dockerfile-production
    ports:
      - ${SUPERVISOR_PYTHON_2_PORT}:${SUPERVISOR_PYTHON_2_PORT}
    environment:
      FLASK_APP: supervisor-python-2
      FLASK_PORT: ${SUPERVISOR_PYTHON_2_PORT}
      FLASK_ENV: production
      FLASK_DEBUG: 0
      WASMIOT_ORCHESTRATOR_URL: ${WASMIOT_ORCHESTRATOR_URL}
      WASMIOT_LOGGING_ENDPOINT: ${WASMIOT_LOGGING_ENDPOINT}
      # EXTERNAL_LOGGING_ENABLED: true
    volumes:
      - ./test1/device-python-2/configs:/app/instance/configs
      - ./test1/device-python-2/modules:/app/instance/modules
      - ./test1/device-python-2/output:/app/instance/output
    networks:
      wasmiot:
        ipv4_address: 172.21.0.22

  supervisor-rust-1:
    image: ghcr.io/liquidai-project/supervisor-rust-port
    container_name: wasmiot-supervisor-rust-1
    restart: unless-stopped
    depends_on:
      - orchestrator
    build:
      context: ../supervisor-rust-port
      dockerfile: ./Dockerfile
    ports:
      - ${SUPERVISOR_RUST_1_PORT}:${SUPERVISOR_RUST_1_PORT}
    environment:
      SUPERVISOR_NAME: supervisor-rust-1
      WASMIOT_SUPERVISOR_PORT: ${SUPERVISOR_RUST_1_PORT}
      WASMIOT_ORCHESTRATOR_URL: ${WASMIOT_ORCHESTRATOR_URL}
      WASMIOT_LOGGING_ENDPOINT: ${WASMIOT_LOGGING_ENDPOINT}
      EXTERNAL_LOGGING_ENABLED: true
      DEFAULT_URL_SCHEME: http
      WASMIOT_SUPERVISOR_IP: 172.21.0.31
    volumes:
      - ./test1/device-rust-1/configs:/app/instance/configs
      - ./test1/device-rust-1/modules:/app/instance/modules
      - ./test1/device-rust-1/output:/app/instance/output
    networks:
      wasmiot:
        ipv4_address: 172.21.0.31

  supervisor-rust-2:
    image: ghcr.io/liquidai-project/supervisor-rust-port
    container_name: wasmiot-supervisor-rust-2
    restart: unless-stopped
    depends_on:
      - orchestrator
    build:
      context: ../supervisor-rust-port
      dockerfile: ./Dockerfile
    ports:
      - ${SUPERVISOR_RUST_2_PORT}:${SUPERVISOR_RUST_2_PORT}
    environment:
      SUPERVISOR_NAME: supervisor-rust-2
      WASMIOT_SUPERVISOR_PORT: ${SUPERVISOR_RUST_2_PORT}
      WASMIOT_ORCHESTRATOR_URL: ${WASMIOT_ORCHESTRATOR_URL}
      WASMIOT_LOGGING_ENDPOINT: ${WASMIOT_LOGGING_ENDPOINT}
      EXTERNAL_LOGGING_ENABLED: true
      DEFAULT_URL_SCHEME: http
      WASMIOT_SUPERVISOR_IP: 172.21.0.32
    volumes:
      - ./test1/device-rust-2/configs:/app/instance/configs
      - ./test1/device-rust-2/modules:/app/instance/modules
      - ./test1/device-rust-2/output:/app/instance/output
    networks:
      wasmiot:
        ipv4_address: 172.21.0.32

volumes:
  mongo-config:
    name: wasmiot-mongo-config-test
  mongo-db:
    name: wasmiot-mongo-db-test

networks:
  wasmiot:
    name: wasmiot-net-test
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
  database:
    name: wasmiot-database-net-test
