services:
  mongo:
    image: mongo:6.0.23
    container_name: wasmiot-mongodb
    restart: unless-stopped
    networks:
      database:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-config:/data/configdb
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: wasmiot-mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:-mongo}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${MONGO_EXPRESS_ENABLE_ADMIN:-false}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH: ${MONGO_EXPRESS_BASICAUTH:-false}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    networks:
      database:

  mdns-reflector:
    image: flungo/avahi:main
    container_name: wasmiot-mdns-reflector
    restart: unless-stopped
    environment:
      REFLECTOR_ENABLE_REFLECTOR: "yes"
    networks:
      wasmiot-main:
        ipv4_address: ${INTERNAL_MDNS_REFLECTOR_IP}

  orchestrator:
    image: ghcr.io/liquidai-project/wasmiot-orchestrator
    container_name: wasmiot-orchestrator
    restart: unless-stopped
    depends_on:
      - mongo
    build:
      context: ../fileserv
      dockerfile: ./Dockerfile-production
    networks:
      wasmiot-main:
        ipv4_address: ${INTERNAL_ORCHESTRATOR_IP}
      database:
    extra_hosts:
      - ${HOST_ADDRESS}:host-gateway
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      PUBLIC_HOST: ${ORCHESTRATOR_PUBLIC_HOST}
      PUBLIC_PORT: ${ORCHESTRATOR_PUBLIC_PORT}
      WASMIOT_INIT_FOLDER: ${WASMIOT_INIT_FOLDER:-/init}
      WASMIOT_CLEAR_LOGS: ${WASMIOT_CLEAR_LOGS:-true}
      WASMIOT_USE_WEB_SOCKETS: ${WASMIOT_USE_WEB_SOCKETS:-true}
    volumes:
      - ./test1/orchestrator/init:/init
      - ./test1/orchestrator/files:/app/fileserv/files

  nginx-proxy:
    image: nginx:1.27.5
    container_name: wasmiot-nginx
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
    environment:
      ORCHESTRATOR_IP: ${INTERNAL_ORCHESTRATOR_IP}
      ORCHESTRATOR_PORT: ${ORCHESTRATOR_PUBLIC_PORT}
    volumes:
      - ./test1/orchestrator/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./test1/orchestrator/nginx/templates/10-variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
    networks:
      wasmiot-main:
        ipv4_address: ${INTERNAL_NGINX_IP}

  mdns-server:
    image: ghcr.io/liquidai-project/wasmiot-mdns-server
    container_name: wasmiot-mdns-server
    restart: unless-stopped
    build:
      context: ./mdns-server
      dockerfile: ./Dockerfile
    networks:
      wasmiot-main:
        ipv4_address: ${INTERNAL_MDNS_SERVER_IP}

  supervisor-python:
    image: ghcr.io/liquidai-project/wasmiot-supervisor
    container_name: wasmiot-supervisor-python
    restart: unless-stopped
    depends_on:
      - orchestrator
    build:
      context: ../wasmiot-supervisor
      dockerfile: ./Dockerfile-production
    ports:
      - ${SUPERVISOR_PYTHON_DOCKER_PORT}:${SUPERVISOR_PYTHON_DOCKER_PORT}
    environment:
      FLASK_APP: ${SUPERVISOR_PYTHON_DOCKER_NAME}
      FLASK_PORT: ${SUPERVISOR_PYTHON_DOCKER_PORT}
      FLASK_ENV: production
      FLASK_DEBUG: 0
      # WASMIOT_ORCHESTRATOR_URL: ${WASMIOT_ORCHESTRATOR_URL}
      WASMIOT_LOGGING_ENDPOINT: ${WASMIOT_LOGGING_ENDPOINT}
      EXTERNAL_LOGGING_ENABLED: true
    volumes:
      - ./test1/device-python-docker/configs:/app/instance/configs
      - ./test1/device-python-docker/modules:/app/instance/modules
      - ./test1/device-python-docker/output:/app/instance/output
    networks:
      wasmiot-main:
        ipv4_address: ${INTERNAL_SUPERVISOR_PYTHON_IP}
    extra_hosts:
      - ${HOST_ADDRESS}:host-gateway

  supervisor-rust:
    image: ghcr.io/liquidai-project/supervisor-rust-port
    container_name: wasmiot-supervisor-rust
    restart: unless-stopped
    depends_on:
      - orchestrator
    build:
      context: ../supervisor-rust-port
      dockerfile: ./Dockerfile
    ports:
      - ${SUPERVISOR_RUST_DOCKER_PORT}:${SUPERVISOR_RUST_DOCKER_PORT}
    environment:
      SUPERVISOR_NAME: ${SUPERVISOR_RUST_DOCKER_NAME}
      WASMIOT_SUPERVISOR_PORT: ${SUPERVISOR_RUST_DOCKER_PORT}
      # WASMIOT_ORCHESTRATOR_URL: ${WASMIOT_ORCHESTRATOR_URL}
      WASMIOT_LOGGING_ENDPOINT: ${WASMIOT_LOGGING_ENDPOINT}
      EXTERNAL_LOGGING_ENABLED: true
    volumes:
      - ./test1/device-rust-docker/configs:/app/instance/configs
      - ./test1/device-rust-docker/modules:/app/instance/modules
      - ./test1/device-rust-docker/output:/app/instance/output
    networks:
      wasmiot-main:
        ipv4_address: ${INTERNAL_SUPERVISOR_RUST_IP}
    extra_hosts:
      - ${HOST_ADDRESS}:host-gateway

volumes:
  mongo-config:
    name: wasmiot-mongo-config-test
  mongo-db:
    name: wasmiot-mongo-db-test

networks:
  wasmiot-main:
    name: wasmiot-net-main
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
  database:
    name: wasmiot-database-net-test
